#!/usr/bin/env bash

if [ "$1" = "" ]; then
  echo "argument not provided"
fi

if [ "$1" = "gruvbox" ]; then
  echo "setting the colourscheme to gruvbox"
  sleep 2
  # change ghostty
  cd ~/.config/ghostty
  rm config
  cp colours/gruvbox.config config
  # change neovim
  cd ~/.config/nvim
  rm lua/config/colour.lua
  cp colours/gruvbox.lua lua/config/colour.lua
  cd ~
  killall ghostty
fi

if [ "$1" = "gruber-darker" ]; then
  echo "setting the colourscheme to gruber-darker"
  sleep 2
  # change ghostty
  cd ~/.config/ghostty
  rm config
  cp colours/gruber.config config
  # change neovim
  cd ~/.config/nvim
  rm lua/config/colour.lua
  cp colours/gruber.lua lua/config/colour.lua
  cd ~
  killall ghostty
fi
